In [28]:
import os
import pandas as pd
import numpy as np
from datetime import datetime, timedelta, date
import matplotlib.pyplot as plt
import seaborn as sns
import re
import sklearn

# [RAF].rolling(60).sum()
root_path = '../../../data/imputed-data/Vlz-Bagbaguin_00174731/2020/07'
#'../../../data/cleaned-data/Vlz-Bagbaguin_00174731/2020/07/2020-07-21/data.csv'
today = '2020-07-21'
yesterday = date.fromisoformat(today) - timedelta(days=1)
df_today = pd.read_csv(root_path + f'/{today}/data.csv', index_col='Datetime')
yesterday_path = root_path + f'/{yesterday}/data.csv'
if os.path.exists(yesterday_path):
    df_yesterday = pd.read_csv(yesterday_path, index_col='Datetime')
    df = pd.concat([df_yesterday, df_today])
    df["hour-rain"] = df["RAF"].rolling(60, min_periods=1).sum()
    df_today["hour-rain"] = df["hour-rain"].loc[df_today.index]
    df_today.to_csv('test.csv')
    
df.tail()

,RAF,RA1,RI1,ERA,CRA,AT1,RH1,PRS,SLP,WD1,WDM,WS1,WSM,WND,WNS,SOL,WET,WBG,WEA,hour-rain
Datetime,,,,,,,,,,,,,,,,,,,,
2020-07-21 T23:55 Z,0.0,0.0,0.0,0.0,0.0,30.113225,51.4471,1008.564733,1011.487819,199.675174,197.531323,0.511485,0.97993,203.99884,0.511369,120.280742,0.238979,26.862413,1.793503,0.0
2020-07-21 T23:56 Z,0.0,0.0,0.0,0.0,0.0,30.113225,51.4471,1008.564733,1011.487819,199.675174,197.531323,0.511485,0.97993,203.99884,0.511369,120.280742,0.238979,26.862413,1.793503,0.0
2020-07-21 T23:57 Z,0.0,0.0,0.0,0.0,0.0,30.113225,51.4471,1008.564733,1011.487819,199.675174,197.531323,0.511485,0.97993,203.99884,0.511369,120.280742,0.238979,26.862413,1.793503,0.0
2020-07-21 T23:58 Z,0.0,0.0,0.0,0.0,0.0,30.113225,51.4471,1008.564733,1011.487819,199.675174,197.531323,0.511485,0.97993,203.99884,0.511369,120.280742,0.238979,26.862413,1.793503,0.0
2020-07-21 T23:59 Z,0.0,0.0,0.0,0.0,0.0,30.113225,51.4471,1008.564733,1011.487819,199.675174,197.531323,0.511485,0.97993,203.99884,0.511369,120.280742,0.238979,26.862413,1.793503,0.0

In [24]:
df.index == df_today.index
#df_today.index

ValueError: Lengths must match to compare